- platform: mqtt
  state_topic: "hass/wemos_1/temperature"
  name: "MQTT Temperature"
  qos: "1"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: "hass/wemos_1/humidity"
  name: "MQTT Humidity"
  qos: "1"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity }}'
